const KBarActions = (router) => [
  {
    id: "homeAction",
    name: "Home",
    shortcut: ["h"],
    keywords: "home",
    section: "Navigation",
    perform: () => router.push("/"),
  },
  {
    id: "aboutAction",
    name: "About",
    shortcut: ["ab"],
    keywords: "about",
    section: "Navigation",
    perform: () => router.push("/about"),
  },
  {
    id: "aboutWebAction",
    name: "About this website",
    shortcut: ["web"],
    keywords: "website",
    section: "Navigation",
    perform: () => router.push("/about-this-website"),
  },
  {
    id: "antilibraryAction",
    name: "Antilibrary",
    shortcut: ["an"],
    keywords: "anti",
    section: "Navigation",
    perform: () => router.push("/antilibrary"),
  },
  {
    id: "blogAction",
    name: "Blog",
    shortcut: ["bl"],
    keywords: "blog",
    section: "Navigation",
    perform: () => router.push("/blog"),
  },
  {
    id: "booksAction",
    name: "Books",
    shortcut: ["bo"],
    keywords: "books",
    section: "Navigation",
    perform: () => router.push("/books"),
  },
  {
    id: "favoritesAction",
    name: "Favorites",
    shortcut: ["f"],
    keywords: "favorites",
    section: "Navigation",
    perform: () => router.push("/favorites"),
  },
  {
    id: "moviesAction",
    name: "Movies",
    shortcut: ["m"],
    keywords: "movies",
    section: "Navigation",
    perform: () => router.push("/movies"),
  },
  {
    id: "nowAction",
    name: "Now",
    shortcut: ["n"],
    keywords: "now",
    section: "Navigation",
    perform: () => router.push("/now"),
  },
  {
    id: "portfolioAction",
    name: "Portfolio",
    shortcut: ["p"],
    keywords: "portfolio",
    section: "Navigation",
    perform: () => router.push("/portfolio"),
  },
  {
    id: "recipeAction",
    name: "Recipe Book",
    shortcut: ["r"],
    keywords: "recipe",
    section: "Navigation",
    perform: () => router.push("/recipe-book"),
  },
  {
    id: "twitterAction",
    name: "Twitter",
    shortcut: ["t"],
    keywords: "social contact dm",
    section: "Navigation",
    perform: () => window.open("https://twitter.com/clara__le", "_blank"),
  },
];
export default KBarActions;
