// {
//   date: "",
//   title: "",
//   author: "",
//   isbn: "",
//   notes: ""
// },

export default [
  {
    date: "2021-01-10 13:16:05",
    title: "Straw Dogs",
    author: "John Gray",
    isbn: "9781862075962",
    notes:
      "Straw Dogs by the English philosopher John Gray challenged Norbauer's view on <q>pretty much everything</q>. The book is a critique of philosophical humanism. Recommendation from https://www.densediscovery.com/issues/119/",
  },
  {
    date: "2021-01-02 18:22:10",
    title: "Children of Time",
    author: "Adrian Tchaikovsky",
    isbn: "9780316452502",
    notes:
      "Space odyssey kind of book, civilization building among the stars. It reminded me of Seveneves. Found in the sci-fi section of Dussman",
  },
  {
    date: "2021-01-02 18:19:18",
    title: "Sleep Donation",
    author: "Karen Russell",
    isbn: "0525566082",
    notes:
      "When an insomnia epidemic sets in the near future. The only solution is for healthy people to “donate” their sleep. Stephen King said he had nightmares reading this book. Discovered in the dystopia section of Dussman",
  },
  {
    date: "2021-01-02 18:09:16",
    title: "The Berlin Stories",
    author: "Christopher Isherwood",
    isbn: "0811200701",
    notes:
      "Isherwood was an Anglo-American novelist born in 1904. He captures the Berlin atmosphere of the 30s with its charming cafés, intrigues, and nightlife. Discovered in the Berlin section of Dussman",
  },
  {
    date: "2020-12-21",
    title: "Generative Design",
    author: "Benedikt Gross",
    isbn: "1616897589",
    notes:
      "Data art generated by computer using the P5.js library. The book includes a gentle tutorial on how to get started, but also a bunch of “recipes” for making cool things that you can tweak to generate interesting results. Recommended by https://blog.duncangeere.com/generative-design/",
  },
  {
    date: "2020-12-14",
    title: "Wabi-Sabi for Artists, Designers, Poets & Philosophers",
    author: "Leonard Koren",
    isbn: "1880656124",
    notes:
      "Wabi-sabi is a Japanese concept describing the appreciation of things imperfect, impermanent, and incomplete. It is a short meditative read that might help me to let go and be a bit less of a perfectionist. Recommended by www.densediscovery.com/issues/118",
  },
  // {
  //   date: "2020-12-14",
  //   title: "The Art of Frugal Hedonism",
  //   author: "Annie Raser-Rowland, Adam Grubb",
  //   isbn: "9780994392817",
  //   notes: "Written by an Australian couple, this self-help book sounds like a light-hearted (and funny) read about living better with less. High-priority on my to-read list. Recommended by www.densediscovery.com/issues/118"
  // },
];
